#!/bin/node
var fs = require('fs')
var mime = require('./mime.js')

var contents = '//this file was generated by browserify-mime'
 + '\n"use strict"'
 + '\nvar mime = module.exports = {'
 + '\n    lookup: ' + mime.lookup.toString()
 + '\n  , default_type: "' + mime.default_type + '"'
 + '\n  , types: ' + JSON.stringify(mime.types,null,2) + ''
 + '\n  , extensions: ' + JSON.stringify(mime.extensions,null,2) + ''
 + '\n  , extension: ' + mime.extension.toString()
 + '\n  , define: ' + mime.define.toString().replace('process.env.DEBUG_MIME', 'false')
 + '\n  , charsets: {lookup: ' + mime.charsets.lookup.toString() + '}'
 + '\n}'

//these two lines are so the tests pass
 + '\nmime.types.constructor = undefined'
 + '\nmime.extensions.constructor = undefined'

fs.writeFileSync('browserify-mime.js', contents)
